
---
- name: Create mastodon data and backup directories
  become: yes
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    recurse: "{{ item.recurse }}"
  with_items:
    - { path: "{{ mastodon_public_path }}", recurse: no, mode: '0777'}
    - { path: "{{ backup_folder }}", recurse: no, mode: '0777'}

- name: Create mastodon files
  become: yes
  template:
    src: "{{ item.template }}.j2"
    dest: "{{ item.path }}/{{ item.template }}"
    mode: "{{ item.mode }}"
  with_items:
    - { template: docker-compose-mastodon.yml , path: "{{ node_home }}", mode: '0644' }
    - { template: mastodon-backup.sh , path: "{{ node_home }}", mode: '0777' }
    - { template: mastodon-clean.sh , path: "{{ node_home }}", mode: '0777' }
    - { template: mastodon.env , path: "{{ node_home }}", mode: '0644' }
    - { template: comwork.rake , path: "{{ node_home }}", mode: '0644' }

- name: Run the containers
  become: yes
  command: "docker-compose -f {{ node_home }}/docker-compose-mastodon.yml up -d --force-recreate"

- name: Creates clean cron
  ansible.builtin.cron:
    name: mastodon clean cron
    minute: "0"
    hour: "2"
    user: root
    job: "bash {{ node_home }}/mastodon-clean.sh"
    cron_file: ansible_mastodon_clean
